### ISSUE TITLE
Setting step size of regulariser

### ISSUE THREAD

**Issue by SohamTamba** [dgilton/neumann_networks_code#1]
I'm looking at the [code of the Neumann network](https://github.com/dgilton/neumann_networks_code/blob/master/src/neumann_network.py) and I don't see how one can set the step size of the regulariser, $\textrtailn$.

I'm refering to the equation: 

$$\beta^{0} = \textrtailn * X^{T} * y$$

**Comment by dgilton** [comment]
Hi Soham,
See Line 47 in https://github.com/dgilton/neumann_networks_code/blob/master/src/neumann_network.py
Our code treats \eta as a learned parameter, and attempts to learn it via backpropagation. If you want to fix it to a particular value, change  the line 
self.eta = tf.get_variable(name='eta', initializer=0.1, dtype=tf.float32, trainable=True)
to 
self.eta = tf.get_variable(name='eta', initializer=0.1, dtype=tf.float32, trainable=False)
and initialize it to the value you want.
We assume that the regularizer implicitly learns an eta, but if you'd like to attempt to fix the regularization scaling (and not the general stepsize) you can also multiply the learned_component variable by some fixed scalar.

**Comment by SohamTamba** [comment]
Thanks for the quick reply 😄
